[colors.bright]
black = "#2e3436"
blue = "#729fcf"
cyan = "#34e2e2"
green = "#8ae234"
magenta = "#ad7fa8"
red = "#ef2929"
white = "#eeeeec"
yellow = "#fce94f"

[colors.normal]
black = "#2e3436"
blue = "#3465a4"
cyan = "#06989a"
green = "#73d216"
magenta = "#75507b"
red = "#cc0000"
white = "#d3d7cf"
yellow = "#edd400"

[colors.primary]
background = "#000000"
foreground = "#00ff00"

[font]
size = 13.0

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_title = true
opacity = 0.9
title = "Alacritty"
